name       : perl-test-utf8
version    : 1.01
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/M/MA/MARKF/Test-utf8-1.01.tar.gz : ef371b1769cd8d36d2d657e8321723d94c8f8d89e7fd7437c6648c5dc6711b7a
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::utf8 - handy utf8 tests
description: |
    This module is a collection of tests useful for dealing with utf8 strings in Perl. This module has two types of tests: The validity tests check if a string is valid and not corrupt, whereas the characteristics tests will check that string has a given set of characteristics.
builddeps  :
    - perl-module-install
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
